FROM node:20-alpine

WORKDIR /app

# Copiar package files
COPY package*.json ./

# Instalar dependencias
RUN npm install

# El código fuente se montará como volumen
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
